USE [master]
GO

/****** Object:  Database [DbInventario]    Script Date: 12/11/2023 11:53:42 ******/
CREATE DATABASE [DbInventario]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DbInventario3_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\DbInventario3.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DbInventario3_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\DbInventario3.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DbInventario].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DbInventario] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DbInventario] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DbInventario] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DbInventario] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DbInventario] SET ARITHABORT OFF 
GO

ALTER DATABASE [DbInventario] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [DbInventario] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DbInventario] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DbInventario] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DbInventario] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DbInventario] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DbInventario] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DbInventario] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DbInventario] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DbInventario] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DbInventario] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DbInventario] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DbInventario] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DbInventario] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DbInventario] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DbInventario] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DbInventario] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DbInventario] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DbInventario] SET  MULTI_USER 
GO

ALTER DATABASE [DbInventario] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DbInventario] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DbInventario] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DbInventario] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DbInventario] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DbInventario] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DbInventario] SET QUERY_STORE = ON
GO

ALTER DATABASE [DbInventario] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [DbInventario] SET  READ_WRITE 
GO


